list: $/tb/catalog/models/attribute/columns.yaml
modelClass: Tb\Catalog\Models\Attribute
title: 'tb.catalog::lang.models.attribute.label_plural'
recordUrl: tb/catalog/attributes/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
perPageOptions: [20, 40, 80, 100, 120]
showPageNumbers: true
showSetup: true
showSorting: true
# Default sorting column
# defaultSort:
#     column: created_at
#     direction: desc
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
