variants:
    label: tb.catalog::lang.models.product_variant.label
    manage:
        form: $/tb/catalog/models/productvariant/fields.yaml
        list: $/tb/catalog/models/productvariant/columns.yaml
    view:
        list: $/tb/catalog/models/productvariant/columns.yaml
        toolbarButtons: create|delete
productattributes:
    label: tb.catalog::lang.models.product_attribute.label
    manage:
        form: $/tb/catalog/models/productattribute/fields.yaml
        list: $/tb/catalog/models/productattribute/columns.yaml
    view:
        list: $/tb/catalog/models/productattribute/columns.yaml
        toolbarButtons: create|delete