list: $/tb/catalog/models/deliverymethod/columns.yaml
modelClass: Tb\Catalog\Models\DeliveryMethod
title: 'tb.catalog::lang.models.deliverymethod.label_plural'
recordUrl: tb/catalog/deliverymethods/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
perPageOptions: [20, 40, 80, 100, 120]
showPageNumbers: true
showSetup: true
showSorting: true
defaultSort:
    column: created_at
    direction: desc
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
